[package]
name = "pdf-wasm-bindings"
version = "0.0.1"
edition = "2024"

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
pdf-wasm = { version = "*", path = ".." }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]