name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */6 * *'
  push:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/configure-pages@v5
      - run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: |
          cd wasm
          RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack build --target web --release
          cp -r ./pkg ./deploy      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'wasm/deploy'
      - uses: actions/deploy-pages@v4