name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */6 * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/deploy.yml"
      - "wasm/deploy/index.html"
      - "Cargo.toml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/configure-pages@v5
      - run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: |
          cp ./assets/favicon.webp ./wasm/deploy
          cd wasm && RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack build --target web --release
          cp -r ./pkg ./deploy
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'wasm/deploy'
      - uses: actions/deploy-pages@v4
      - uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'wasm/deploy'
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"